import 'package:flutter/material.dart';

List<DropdownMenuItem> categoryItems = const [
  DropdownMenuItem(child: Text('Art and design'), value: 'Art and design',),
  DropdownMenuItem(child: Text('Book and writing'), value: 'Book and writing',),
  DropdownMenuItem(child: Text('Business'), value: 'Business',),
  DropdownMenuItem(child: Text('Career'), value: 'Career',),
  DropdownMenuItem(child: Text('DIY craft'), value: 'DIY craft',),
  DropdownMenuItem(child: Text('Fashion and beauty'), value: 'Fashion and beauty',),
  DropdownMenuItem(child: Text('Finance'), value: 'Finance',),
  DropdownMenuItem(child: Text('Food'), value: 'Food',),
  DropdownMenuItem(child: Text('Gaming'), value: 'Gaming',),
  DropdownMenuItem(child: Text('Health and fitness'), value: 'Health and fitness',),
  DropdownMenuItem(child: Text('Interior design'), value: 'Interior design',),
  DropdownMenuItem(child: Text('Lifestyle'), value: 'Lifestyle',),
  DropdownMenuItem(child: Text('Marketing'), value: 'Marketing',),
  DropdownMenuItem(child: Text('Movie'), value: 'Movie',),
  DropdownMenuItem(child: Text('Music'), value: 'Music',),
  DropdownMenuItem(child: Text('News'), value: 'News',),
  DropdownMenuItem(child: Text('Online business'), value: 'Online business',),
  DropdownMenuItem(child: Text('Parenting'), value: 'Parenting',),
  DropdownMenuItem(child: Text('Personal'), value: 'Personal',),
  DropdownMenuItem(child: Text('Pets'), value: 'Pets',),
  DropdownMenuItem(child: Text('Personal Growth'), value: 'Personal Growth',),
  DropdownMenuItem(child: Text('Photography'), value: 'Photography',),
  DropdownMenuItem(child: Text('Political'), value: 'Political',),
  DropdownMenuItem(child: Text('Productivity'), value: 'Productivity',),
  DropdownMenuItem(child: Text('Sports'), value: 'Sports',),
  DropdownMenuItem(child: Text('Religion'), value: 'Religion',),
  DropdownMenuItem(child: Text('Review'), value: 'Review',),
  DropdownMenuItem(child: Text('Tech'), value: 'Tech',),
  DropdownMenuItem(child: Text('Travel'), value: 'Travel',),
  DropdownMenuItem(child: Text('Web Design'), value: 'Web Design',),
  DropdownMenuItem(child: Text('Writing'), value: 'Writing',),
  DropdownMenuItem(child: Text('Others'), value: 'Others',),
];
